"""Exploratory data analysis for node data generated by generate_data.py.

Usage::

    python eda.py --input data/
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from presidio_fl.data import load_node_data, load_test_data


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="EDA on FL node data.")
    parser.add_argument(
        "--input", type=str, default="data/", help="Data directory (default: data/)"
    )
    return parser.parse_args(argv)


def _detect_nodes(input_dir: Path) -> list[int]:
    return sorted(int(p.stem.split("_")[1]) for p in input_dir.glob("node_*_train.csv"))


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    input_dir = Path(args.input)

    if not input_dir.exists():
        print(f"ERROR: data directory '{input_dir}' does not exist.", file=sys.stderr)
        sys.exit(1)

    node_ids = _detect_nodes(input_dir)
    if not node_ids:
        print("ERROR: No node CSV files found in the data directory.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(node_ids)} node(s): {node_ids}")
    summary: dict = {"nodes": {}, "test": {}}

    total_train = 0
    for node_id in node_ids:
        X, y = load_node_data(input_dir, node_id)
        n_samples, n_features = X.shape
        class_dist = {int(c): int((y == c).sum()) for c in sorted(set(y.tolist()))}
        total_train += n_samples
        summary["nodes"][str(node_id)] = {
            "n_samples": n_samples,
            "n_features": n_features,
            "class_distribution": class_dist,
        }
        print(
            f"  Node {node_id}: {n_samples} samples, {n_features} features, "
            f"class distribution={class_dist}"
        )

    X_test, y_test = load_test_data(input_dir)
    n_test, n_features_test = X_test.shape
    test_class_dist = {int(c): int((y_test == c).sum()) for c in sorted(set(y_test.tolist()))}
    summary["test"] = {
        "n_samples": n_test,
        "n_features": n_features_test,
        "class_distribution": test_class_dist,
    }

    print(f"\nTrain total: {total_train} samples")
    print(f"Test set:    {n_test} samples, classes={test_class_dist}")
    print(f"Features:    {n_features_test}")

    out_path = input_dir / "eda_summary.json"
    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=2)
    print(f"\nEDA summary saved to {out_path}")


if __name__ == "__main__":
    main()
